#!/usr/bin/env bash
set -ex

sudo apt install -y fzf fd-find ripgrep

mkdir -p "$HOME/.mike/bin"
cd "$HOME/.mike/bin"

bold() {
  echo -e "\e[1m$@\e[0m"
}

# nvim
if [[ -f 'nvim' ]]; then
  echo 'nvim.appimage already installed'
else
  wget -O 'nvim' 'https://github.com/neovim/neovim/releases/download/v0.4.4/nvim.appimage'
  chmod u+x 'nvim'
fi

echo wow

# tmux
if [[ -f 'tmux' ]]; then
 bold 'tmux.appimage already installed'
else
 wget -O 'tmux' 'https://github.com/nelsonenzo/tmux-appimage/releases/download/tmux3.1b/tmux-3.1b-x86_64.AppImage'
 chmod u+x 'tmux'
fi

# nnn
if [[ -f 'nnn' ]]; then
  bold 'nnn already installed'
else
  wget -O '/tmp/nnn.tar.gz' 'https://github.com/jarun/nnn/releases/download/v3.5/nnn-static-3.5.x86_64.tar.gz'
  tar -xvf '/tmp/nnn.tar.gz'
  chmod u+x 'nnn-static'
  mv 'nnn-static' 'nnn'
fi
