#!/usr/bin/env bash
set -ex

mkdir -p "$HOME/.mike/bin"
cd "$HOME/.mike/bin"

bold() {
  echo -e "\e[1m$@\e[0m"
}

# fzf
if [[ -d ~/.fzf ]]; then
  bold 'fzf already installed'
else
  bold 'downloading fzf'
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
fi

# nvim
nvim_file="nvim.appimage"
nvim_url='https://github.com/neovim/neovim/releases/download/v0.4.4/nvim.appimage'
if [[ -f "$nvim_file" ]]; then
  bold "$nvim_file already installed"
else
  bold "downloading $nvim_file"
  wget -O "$nvim_file" "$nvim_url"
  chmod u+x "$nvim_file"
fi

# tmux
tmux_file="tmux.appimage"
tmux_url='https://github.com/nelsonenzo/tmux-appimage/releases/download/tmux3.1b/tmux-3.1b-x86_64.AppImage'
if [[ -f "$tmux_file" ]]; then
  bold "$tmux_file already installed"
else
  bold "downloading $tmux_file"
  wget -O "$tmux_file" "$tmux_url"
  chmod u+x "$tmux_file"
fi

# nnn 
nnn_url='https://github.com/jarun/nnn/releases/download/v3.5/nnn-static-3.5.x86_64.tar.gz'
if [[ -f 'nnn' ]]; then
  bold 'nnn already installed'
else
  bold 'downloading nnn'
  wget -O '/tmp/nnn.tar.gz' "$nnn_url"
  tar -xvf '/tmp/nnn.tar.gz'
  chmod u+x 'nnn-static' "$nnn_url"
  mv 'nnn-static' 'nnn'
fi

# root stuff, if possible
sudo apt install -y ripgrep fd-find
sudo ln -sf ~/.mike/xkb_symbols /usr/share/X11/xkb/symbols/mike
