#!/usr/bin/env bash
wget -qO ~/.mike/bin/nvim.appimage https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
wget -qO - https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh
