#!/usr/bin/env bash

# Install rootless docker
# https://docs.docker.com/engine/security/rootless/

curl -fsSL https://get.docker.com/rootless | sh

# Install docker-compose 
curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o ~/bin/docker-compose

