#!/usr/bin/env bash
set -ex
[ ! $1 ] && echo 'No input!' && exit 1
new_file="$HOME/.local/scripts/$1"
[ -f "$new_file" ] && echo "Script '$1' already exists" && exit 1
printf "#!/usr/bin/env bash\n[ ! \$1 ] && echo 'No input!' && exit 1\n\n" > "$new_file"
chmod +x "$new_file"
echo "$new_file created"
$EDITOR "$new_file"
