#!/usr/bin/env bash
set -ex

# <ctrl-r> menu
# Press CTRL-R to show menu
# 	- edit script
# 	- edit template
#   - new script
# 	- new template
# 	- open script directory
#   - open template directory
	
mkdir -p ~/.scripts/templates

MENU="\
run script
edit script
edit template
new script
new template
open script directory
open template directory"

echo "$MENU" | fzf

# menu() {
# 	fzf --bind ''
# }
